NFG-308, NFG-307, NFG-305, NFG-310 Add new git hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,11 @@
 #!/bin/sh
+# This hook checks that branches are named according to the convention.
 
-BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
-PATTERN="^(feature|hotfix|release|bugfix|improvement)/NFG-[0-9]+-.+"
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+branch_regex="^(feature|bugfix|hotfix|release)/NFG-[0-9]+-.+$"
 
-if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
-  echo "Error: Branch name '$BRANCH_NAME' does not follow the naming convention."
-  echo "Naming convention: (feature|hotfix|release|bugfix|improvement)/NFG-<issue-number>-<short-description>"
+if ! echo "$current_branch" | grep -Eq "$branch_regex"; then
+  echo "Error: Branch name '$current_branch' does not follow the naming convention."
+  echo "Please rename your branch to follow the convention: (feature|bugfix|hotfix|release)/NFG-123-description."
   exit 1
 fi
